# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Ankudinova_Shibkova' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Lab4
  pod 'Moya', '~> 15.0'

  # or 

  pod 'Moya/RxSwift', '~> 15.0'

  # or

  pod 'Moya/ReactiveSwift', '~> 15.0'

  # or

  pod 'Moya/Combine', '~> 15.0'

end
